package com.classic.project.model.character;

public enum ClassOfCharacter {

    HUMAN_FIGHTER("Human Fighter"),
    WARRIOR("Warrior"),
    HUMAN_KNIGHT("human Knight"),
    ROGUE("ROGUE"),
    WARLORD("Warlord"),
    GLADIATOR("Gladiator"),
    PALADIN("Paladin"),
    DARK_AVENGER("Dark Avenger"),
    TREASURE_HUNTER("Treasure Hunter"),
    HAWKEYE("Hawkeye"),
    DREADNOUGHT("Dreadnought"),
    DUELIST("Duelist"),
    PHOENIX_KNIGHT("Phoenix Knight"),
    HELL_KNIGHT("Hell Knight"),
    ADVENTURER("Adventurer"),
    SAGITTARIUS("Sagittarius"),
    HUMAN_MYSTIC("Human Mystic"),
    HUMAN_WIZARD("Human Wizard"),
    CLERIC("Cleric"),
    SORCERER("Sorcerer"),
    NECRO("Necromancer"),
    WARLOCK("Warlock"),
    BISHOP("Bishop"),
    PROPHET("Prophet"),
    ARCHMAGE("Archmage"),
    SOULTAKER("Soultaker"),
    ARCANA_LORD("Arcana Lord"),
    CARDINAL("Cardinal"),
    HIEROPHANT("Hierophant"),
    ELVEN_FIGHTER("Elven Fighter"),
    ELVEN_KNIGHT("Elven Knight"),
    ELVEN_SCOUT("Elven Scout"),
    TEMPLE_KNIGHT("Temple Knight"),
    SWORD_SINGER("Sword Singer"),
    PLAINS_WALKER("Plains Walker"),
    SILVER_RANGER("Silver Ranger"),
    EVA_TEMPLAR("Eva's Templar"),
    SWORD_MUSE("Sword Muse"),
    WIND_RIDER("Wind Rider"),
    MOONLIGHT_SENTINEL("Moonlight Sentinel"),
    ELVEN_MYSTIC("Elven Mystic"),
    ELVEN_WIZARD("Elven Wizard"),
    ELVEN_ORACLE("Elven Oracle"),
    SPELLSINGER("Spellsinger"),
    ELEMENTAL_SUMMONER("Elemental Summoner"),
    ELVEN_ELDER("Elven Elder"),
    MYSTIC_MUSE("Mystic Muse"),
    ELEMENTAL_MASTER("Elemental Master"),
    EVA_SAINT("Eva'S Saint"),
    DARK_FIGHTER("Dark Fighter"),
    PALUS_KNIGHT("Palus Knight"),
    ASSASSIN("Assassin"),
    SHILLIEN_KNIGHT("Shillien Knight"),
    BLADEDANCER("Bladedancer"),
    ABYSS_WALKER("Abyss Walker"),
    PHANTOM_RANGER("Phantom Ranger"),
    SHILLIEN_TEMPLAR("Shillien Templar"),
    SPECTRAL_DANCER("Spectral Dancer"),
    GHOST_HUNTER("Ghost Hunter"),
    GHOST_SENTINEL("Ghost Sentinel"),
    DARK_MYSTIC("Dark Mystic"),
    DARK_WIZARD("Dark Wizard"),
    SHILLIEN_ORACLE("Shillien Oracle"),
    SPELLHOWLER("Spellhowler"),
    PHANTOM_SUMMONER("Phantom Summoner"),
    SHILLIEN_ELDER("Shillien Elder"),
    STORM_SCREAMER("Storm Screamer"),
    SPECTRAL_MASTER("Spectral Master"),
    SHILLIEN_SAINT("Shillien Saint"),
    ORC_FIGHTER("Orc Fighter"),
    RAIDER("Raider"),
    MONK("Monk"),
    DESTRO("Destroyer"),
    TYRANT("Tyrant"),
    TITAN("Titan"),
    GK("Grand Khavatari"),
    ORC_MYSTIC("Orc Mystic"),
    ORC_SHAMAN("Orc Shaman"),
    OVERLORD("Overlord"),
    WARCRYER("Warcryer"),
    DOMI("Dominator"),
    DOOMCRYER("Doomcryer"),
    DWARVEN_FIGHTER("Dwarven Fighter"),
    SCAVENGER("Scavenger"),
    ARTISAN("Artisan"),
    BOUNTY_HUNTER("Bounty Hunter"),
    WARSMITH("Warsmith"),
    FORTUNE_SEEKER("Fortune Seeker"),
    MAESTRO("Maestro");


    private String className;
    ClassOfCharacter(String className){
        this.className = className;
    }

    public String getName() {
        return this.className;
    }

    public void setName(String name){
        this.className = name;
    }
}
